---
title: "Lab3A"
author: "Nathan Haywood"
date: "9/7/2020"
output: html_document
biolography: bibliography.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
download.file(url = "https://ndownloader.figshare.com/files/2292169", destfile = "portal_data_joined.csv")
```

```{r}
surveys <- read.csv("portal_data_joined.csv")
```

```{r}
head(surveys)
```

```{r, results="hide"}
view(surveys)
```

```{r}
str(surveys)
```

## Challenge 1
#### Class: Dataframe, NumRows: 34786, NumColumns: 13, NumSpecies: 48

```{r, results="hide"}
surveys[1,1]
surveys[1,6]
surveys[,1]
surveys[1]
surveys[1:3,7]
surveys[3,]
head_surveys <- surveys[1:6,]
```

```{r, results="hide"}
surveys[,-1]
surveys[-(7:34786),]
```

```{r, results="hide"}
surveys["species_id"]
surveys[, "species_id"]
surveys[["species_id"]]
surveys$species_id
```

## Challenge 2
```{r}
surveys_200 <- surveys[200,]
lastRow <- surveys[nrow(surveys),]
midRow <- surveys[nrow(surveys) / 2,]
headSurveys <- surveys[-(7:nrow(surveys))]
```

```{r}
sex <- factor(c("male", "female", "female", "male"))
```

```{r}
levels(sex)
nlevels(sex)
```

```{r}
sex
```

```{r}
sex <- factor(sex, levels = c("male", "female"))
sex
```

```{r}
as.character(sex)
```

```{r}
year_fct <- factor(c(1990, 1983, 1977, 1998, 1990))
as.numeric(year_fct)
as.numeric(as.character(year_fct))
as.numeric(levels(year_fct))[year_fct]
```

```{r}
plot(as.factor(surveys$sex))
```

```{r}
sex <- factor(surveys$sex)
head(sex)
```

```{r}
levels(sex)
```

```{r}
levels(sex)[1] <- "undetermined"
levels(sex)
```

```{r}
head(sex)
```

## Challenge 3
```{r}
levels(sex)[2:3] <- c("female", "male")
sex <- factor(sex, levels = c("female", "male", "undetermined"))
plot(sex)
```

```{r}
surveys <- read.csv("portal_data_joined.csv", stringsAsFactors = TRUE)
str(surveys)
surveys <- read.csv("portal_data_joined.csv", stringsAsFactors = FALSE)
str(surveys)
surveys$plot_type <- factor(surveys$plot_type)
```

## Challenge 4
```{r}
animal_data <- data.frame(
          animal = c("dog", "cat", "sea cucumber", "sea urchin"),
          feel = c("furry", "fluffy", "squishy", "spiny"),
          weight = c(45, 8, 1.1, 0.8)
          )
```
#### country: factor, climate: factor, temperature: numeric, norther_hemisphere: factor, has_kangeroo:factor
#### Characters would be vectors if stringsAsFactors=False
#### The 1 in has_kangeroo should be a boolean

```{r}
str(surveys)
```

```{r}
library(lubridate)
```

```{r}
my_date <- ymd("2015-01-01")
str(my_date)
```

```{r}
my_date <- ymd(paste("2015", "1", "1", sep = "-")) 
str(my_date)
```

```{r, results="hide"}
paste(surveys$year, surveys$month, surveys$day, sep = "-")
```

```{r, results="hide"}
ymd(paste(surveys$year, surveys$month, surveys$day, sep = "-"))
```

```{r}
surveys$date <- ymd(paste(surveys$year, surveys$month, surveys$day, sep = "-"))
```

```{r}
str(surveys)
```

```{r}
summary(surveys$date)
```

```{r}
missing_dates <- surveys[is.na(surveys$date), c("year", "month", "day")]
head(missing_dates)
```

## REFERENCES